name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-node:
    uses: microsoft-cloud-ucoe/.github/.github/workflows/reusable-ci-node.yml@main
    with:
      node-version: '20'
  build-python:
    uses: microsoft-cloud-ucoe/.github/.github/workflows/reusable-ci-python.yml@main
    with:
      python-version: '3.12'
