name: Orchestrate Standards and Governance

on:
  schedule:
    - cron: '15 2 * * *'
  workflow_dispatch:

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout orchestrator
        uses: actions/checkout@v4
      - name: Setup Node (for gh and scripts if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install gh CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gh
      - name: Refresh manifest
        shell: pwsh
        run: ./meta-orchestrator/scripts/refresh-repos.ps1 -Org microsoft-cloud-ucoe -Limit 500
      - name: Bootstrap clones
        shell: pwsh
        run: ./meta-orchestrator/scripts/bootstrap.ps1
      - name: Sync standards
        shell: pwsh
        run: ./meta-orchestrator/scripts/sync-standards.ps1 -Parallel
      - name: Apply labels
        shell: pwsh
        run: ./meta-orchestrator/scripts/apply-labels-all.ps1 -Parallel
      - name: Apply branch protection
        shell: pwsh
        run: ./meta-orchestrator/scripts/apply-branch-protection-all.ps1 -Parallel
